#!/bin/bash

# - 1 - On commence par récuperer le statut du replicaSet : un objet JSON sera renvoyé.
# export RESULTAT_JSON_REQUETE_MONGO=mongo mongo/rocketchat --eval "rs.status()"
# (à tester) : 
# export RESULTAT_JSON_REQUETE_MONGO=mongo mongo/rocketchat --eval "rs.status({ _id: ''rs0'', members: [ { _id: 0, host: ''localhost:27017'' } ]})"

export RESULTAT_JSON_REQUETE_MONGO=$(mongo mongo/rocketchat --eval "rs.status({ _id: ''rs0''})")

# - 2 - Ensuite, on vérifie que dans le JSON, on trouve bien mention de l'ID du replicaSet, et on vérifie son statut, le
#       tout en "parsant" le JSON. Pour cela, on doit utiliser la structure de l'output de cette commande, précisé
#       par la documentation ofiicielle : https://docs.mongodb.com/manual/reference/command/replSetGetStatus/#rs-status-output
# -------------------------------------------------------------------------------------------------------------------------
# -- d'après la doc officielle, le JSON retourné coontient l'info du nom de replicaSet, et de son statut "myState" :
# 
# -------------------------------------------------------------------------------------------------------------------------
#           {
#              "set" : "replset",
#              "date" : ISODate("2018-05-13T16:36:54.319Z"),
#              "myState" : 1,
#              etc...
#
# -------------------------------------------------------------------------------------------------------------------------
# 
#    il est donc possible de parcourir l'arbre JSON à l'aide de commandes mongoDB, du genre du find(), pour
#    retrouver le name et le "myState" du replicaSet `rs0`


# -------------------------------------------------------------------------------------------------------------------------
# Donc, si  : 
# 
#     mongo mongo/rocketchat --eval "rs.status({ _id: ''rs0''})"
# 
# retourne une valeur, c'est que le replicaSet "rs0" existe.
# D'après [https://docs.mongodb.com/manual/reference/replica-states/], si le replicaSet existe, il
# doit être dans l'état 1 "PRIMARY", pour que le replicaSet, formé d'une seule réplique, soit prêt à l'emploi pour
# RocketChat :  
# -------------------------------------------------------------------------------------------------------------------------
# Number 	Name 	State Description
# 0 	STARTUP 	Not yet an active member of any set. All members start up in this state. The 
#                       mongod parses the replica # set configuration document while in STARTUP.
# 1 	PRIMARY 	The member in state primary is the only member that can accept write operations. Eligible to vote.
# -------------------------------------------------------------------------------------------------------------------------
# Pour résumer, on attend que la commande retourne une valeur, et même la valeur "1". dans tous les autres cas, on fait
# un "exit 1"

# - 1 - On commence par récuperer le statut du replicaSet : un objet JSON sera renvoyé.
export RESULTAT_JSON_REQUETE_MONGO_RS_EXISTE=$(mongo mongo/rocketchat --eval "rs.status({ _id: 'rs0'})")
# - la commande mongo retournera un JSON, que l ereplicaSet existe, ou non, et quelque soit son état.
# - si la commande mongo échoue, ce n'est donc pas en raison de l'inexistence du replicaSet, alors un
#   code de retour entier, et non un JSON, sera retourné et stocké dans $RESULTAT_JSON_REQUETE_MONGO

echo " MONGO-IINIT-REPLICA >>> CREATE-REPLICASET ===>>> Je vérifie si le replicaSet a déjà été créé "
if [[ $RESULTAT_JSON_REQUETE_MONGO_RS_EXISTE = *"}"* ]]; then
  echo " MONGO-IINIT-REPLICA >>> CREATE-REPLICASET ===>>> Si on trouve une accolade, On a bien un retour JSON, et on vérifie si le replicaSet existe déjà ou non. Sinon, c'est que la commande mongo a échoué, mais pas parceque le replicaSet n'existe pas. "
  echo " DEBUG - [RESULTAT_JSON_REQUETE_MONGO_RS_EXISTE=$RESULTAT_JSON_REQUETE_MONGO_RS_EXISTE] "
  # si la ligne "ok", contient le chiffre "0", c'est que le replicaSet 'rs0' n'a pas encore été initialisé
  RESULTAT_JSON_REQUETE_MONGO_RS_EXISTE=$(mongo mongo/rocketchat --eval "rs.status({ _id: 'rs0'}).ok")
  if [ "$RESULTAT_JSON_REQUETE_MONGO_RS_EXISTE" == "1" ]; then
    # le replicaSet existe déjà, on  vérifie son état avec la commande :
    export ETAT_DU_REPLICASET=$(mongo mongo/rocketchat --eval "rs.status({ _id: 'rs0'}).myState")
    if [ "$REPLICASET" == "1" ]; then
      # Le replicaSet existe bel et bien, dans l'état "1" (PRIMARY), donc on sort donc avec le code de retour zéro.
      exit 0
    else
      # Le replicaSet existe bel et bien, mais n'est pas dans l'état "1" (PRIMARY), donc on sort donc avec le code de retour 1.
      exit 1
  fi
else
  echo "  "
  echo " VERIF : RESULTAT_JSON_REQUETE_MONGO_RS_EXISTE=$RESULTAT_JSON_REQUETE_MONGO_RS_EXISTE "
  echo "  "
  echo " MONGO-IINIT-REPLICA >>> CREATE-REPLICASET ===>>> La commande mondo a foiré, mais pas parce que le replicaSet est inexistantOn a bien un retour JSON "
  echo "  "
  exit 1
fi


