#!/bin/bash

# - 1 - On commence par récuperer le statut du replicaSet : un objet JSON sera renvoyé.
# export RESULTAT_JSON_REQUETE_MONGO=mongo mongo/rocketchat --eval "rs.status()"
# (à tester) : 
# export RESULTAT_JSON_REQUETE_MONGO=mongo mongo/rocketchat --eval "rs.status({ _id: ''rs0'', members: [ { _id: 0, host: ''mongo:27017'' } ]})"

export RESULTAT_JSON_REQUETE_MONGO=$(mongo mongo/rocketchat --eval "rs.status({ _id: 'rs0'})")

# - 2 - Ensuite, on vérifie que dans le JSON, on trouve bien mention de l'ID du replicaSet, et on vérifie son statut, le
#       tout en "parsant" le JSON. Pour cela, on doit utiliser la structure de l'output de cette commande, précisé
#       par la documentation ofiicielle : https://docs.mongodb.com/manual/reference/command/replSetGetStatus/#rs-status-output
# -------------------------------------------------------------------------------------------------------------------------
# -- d'après la doc officielle, le JSON retourné coontient l'info du nom de replicaSet, et de son statut "myState" :
# 
# -------------------------------------------------------------------------------------------------------------------------
#           {
#              "set" : "replset",
#              "date" : ISODate("2018-05-13T16:36:54.319Z"),
#              "myState" : 1,
#              etc...
#
# -------------------------------------------------------------------------------------------------------------------------
# 
#    il est donc possible de parcourir l'arbre JSON à l'aide de commandes mongoDB, du genre du find(), pour
#    retrouver le name et le "myState" du replicaSet `rs0`


# -------------------------------------------------------------------------------------------------------------------------
# Donc, si  : 
# 
#     mongo mongo/rocketchat --eval "rs.status({ _id: ''rs0''})"
# 
# retourne une valeur, c'est que le replicaSet "rs0" existe.
# D'après [https://docs.mongodb.com/manual/reference/replica-states/], si le replmicaSet existe, il
# doit être dans l'état 1 "PRIMARY", pour que le replicaSet, formé d'une seule réplique, soti prêt à l'emploi pour
# RocketChat :  
# -------------------------------------------------------------------------------------------------------------------------
# Number 	Name 	State Description
# 0 	STARTUP 	Not yet an active member of any set. All members start up in this state. The 
#                       mongod parses the replica # set configuration document while in STARTUP.
# 1 	PRIMARY 	The member in state primary is the only member that can accept write operations. Eligible to vote.
# -------------------------------------------------------------------------------------------------------------------------
# Pour résumer, on attend que la commande retourne une valeur, et même la valeur "1". dans tous les autres cas, on fait
# un "exit 1"


# - 1 - On commence par récuperer le statut du replicaSet : un objet JSON sera renvoyé.
export RESULTAT_JSON_REQUETE_MONGO_RS_EXISTE=$(mongo mongo/rocketchat --eval "rs.status({ _id: 'rs0'}).ok"|grep -v mongo|grep -v Mongo)
# export ETAT_DU_REPLICASET=$(mongo mongo/rocketchat --eval "rs.status({ _id: 'rs0'}).myState" | grep -v mongo|grep -v Mongo)

# - la commande mongo retournera un JSON, que l ereplicaSet existe, ou non, et quelque soit son état.
# - si la commande mongo échoue, ce n'est donc pas en raison de l'inexistence du replicaSet, alors un
#   code de retour entier, et non un JSON, sera retourné et stocké dans $RESULTAT_JSON_REQUETE_MONGO

echo " MONGO-IINIT-REPLICA >>> HEALTHCHECK-REPLICASET ===>>> Je vérifie si le replicaSet a déjà été créé "
if [[ $RESULTAT_JSON_REQUETE_MONGO_RS_EXISTE = *"ok"* ]]; then
  echo " MONGO-IINIT-REPLICA >>> HEALTHCHECK-REPLICASET ===>>> On a bien un retour JSON, on vérifie si le replicaSet existe déjà ou non "
  echo " DEBUG - [RESULTAT_REQUETE_MONGO=$RESULTAT_REQUETE_MONGO] "
  # si la ligne "ok", contient le chiffre "0", c'est que le replicaSet 'rs0' n'a pas encore été initialisé
  if [ "$RESULTAT_JSON_REQUETE_MONGO_RS_EXISTE" == "1" ]; then
    # le replicaSet existe déjà, on vérifie son état avec la commande :
    export ETAT_DU_REPLICASET=$(mongo mongo/rocketchat --eval "rs.status({ _id: 'rs0'}).myState" | grep -v mongo|grep -v Mongo)
    if [ "$RESULTAT_JSON_REQUETE_MONGO_RS_EXISTE" == "1" ]; then
      # Le replicaSet existe bel et bien, et est dans l'état "1" (PRIMARY) on sort donc avec le code de retour zéro.
      exit 0
    fi
  else
    echo "  => le replicaSet [rs0] n'a même pas encore été créé dans l'hôte MongoDB [mongo:27017]: Il est temps de le créer !  "
  fi
else
  echo " MONGO-IINIT-REPLICA >>> HEALTHCHECK-REPLICASET ===>>> La commande mondo a foiré, mais pas parce que le replicaSet est inexistantOn a bien un retour JSON "
  exit 1
fi
